# CREATE DB
drop_db_p = """DROP TABLE IF EXISTS PROJECTION"""
drop_db_m = """DROP TABLE IF EXISTS MOVIE"""
drop_db_u = """DROP TABLE IF EXISTS USER"""
drop_db_r = """DROP TABLE IF EXISTS RESERVATION"""

create_movies_table = """
CREATE TABLE IF NOT EXISTS MOVIE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  RAITING REAL NOT NULL)
"""

create_projections_table = """
CREATE TABLE IF NOT EXISTS PROJECTION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MOVIE_ID INTEGER NOT NULL,
  TYPE TEXT NOT NULL,
  M_DATE TEXT NOT NULL,
  M_TIME TEXT NOT NULL,
  FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
)
"""

create_users_table = """
CREATE TABLE IF NOT EXISTS USER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL
)
"""

create_reservations_table = """
CREATE TABLE IF NOT EXISTS RESERVATION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER NOT NULL,
  PROJECTION_ID INTEGER NOT NULL,
  ROW INTEGER NOT NULL,
  COL INTEGER NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY(PROJECTION_ID) REFERENCES PROJECTIONS(ID)
)
"""


# MOVIES
get_movies_by_rate = '''SELECT *
FROM MOVIE
ORDER BY(raiting)'''

get_movie_projections_data = '''SELECT *
FROM MOVIE
WHERE m_date == ?
ORDER BY (m_date)'''

# USERS
get_user = '''SELECT *
FROM USER
WHERE name = ? and password = ?
'''

create_user = '''INSERT
INTO USER
VALUES (?, ?)
'''

check_name = '''SELECT *
FROM USER
WHERE name = ?
'''
