# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170208_1934'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attending',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
